name = "neupane-y-associates-landing-page"
pages_build_output_dir = "dist"

[build]
command = "pnpm build"
cwd = "."
watch_paths = ["src/**/*.{astro,ts,tsx,jsx,js,md}"]

[env.production]
name = "neupane-y-associates-landing-page"
routes = [
  { pattern = "neupaney.com", zone_name = "neupaney.com" },
  { pattern = "*.neupaney.com", zone_name = "neupaney.com" }
]
