name = "neupane-y-associates-landing-page"
type = "javascript"
main = "src/index.ts"

[build]
command = "pnpm build"
cwd = "."
watch_paths = ["src/**/*.{astro,ts,tsx,jsx,js,md}"]

[env.production]
name = "neupane-y-associates-landing-page"
routes = [
  { pattern = "neupane-y-associates.com", zone_name = "neupane-y-associates.com" },
  { pattern = "*.neupane-y-associates.com", zone_name = "neupane-y-associates.com" }
]
